---
- hosts: all
  handlers:
  - import_tasks: handlers/handlers.yml
  tasks:
  - debug: msg="System {{ inventory_hostname }} with fqdn {{ ansible_fqdn}} has uuid {{ ansible_product_uuid }}"
  - authorized_key: user=root state=present key="{{ lookup('file', '/home/moe/.ssh/ed25519.pub') }}"
  - apt: upgrade=dist update_cache=yes autoclean=yes autoremove=yes
  - apt: state=latest name=chrony,tmux,unattended-upgrades,fail2ban,acl

  - template: src=templates/sshd_config.j2 dest=/etc/ssh/sshd_config
    notify: restart ssh
  - group: name=sftponly

- import_playbook: webservers.yml
- import_playbook: databases.yml
- import_playbook: mailservers.yml

- import_playbook: reichstein.yml
- import_playbook: denk.yml

# - hosts: example.com
#   handlers:
#   - import_tasks: handlers/handlers.yml
#   tasks:
#   - { import_tasks: virtual-domain.yml, vars: [ domain: example.com,  db_name: example_com,  db_pass: ExamPlEDbPass1337!, mailbox: false, mail_forward: example.com+forward@gmail.com ]}
#   - { import_tasks: virtual-domain.yml, vars: [ domain: example2.com, db_name: example2_com, db_pass: 1337ExamPlEDbPass!, mailbox: true ]}
#   - copy: 
#       dest: /var/vmail/auth.d/example2.com/passwd
#       content: |
#         info@example2.com:{SSHA256}foobar::::::userdb_quota_rule=*:storage=1G userdb_acl_groups=PublicMailboxAdmins
#     tags: mail