---
#- ansible.builtin.debug: var=ansible_facts
- hostname: name={{ inventory_hostname_short }}
- copy: dest=/etc/hostname content="{{ inventory_hostname_short }}"
- timezone: hwclock=UTC name=UTC

- authorized_key: user=root state=present key="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPMakRtYNU2Dr/7EvrNPb6oUMPJob7VonBomBKejqBu4 moe@rtfm"
- lineinfile: path=/etc/hosts create=yes line="127.0.1.1 {{ inventory_hostname }} {{ inventory_hostname_short }}"

- locale_gen: name=en_US.UTF-8 state=present

- file: path=/var/log/journal/ owner=root group=root mode=u=rX,g=,o= state="directory"
  when: arch == "amd64"
- apt: state=absent name=rsyslog

- apt: upgrade=dist update_cache=yes autoclean=yes autoremove=yes
- apt: state=latest name=chrony,tmux,unattended-upgrades,fail2ban,python3-systemd,acl,zstd,vim,htop,mtr,lsof,speedtest-cli,unzip,python3-pip

- template: src=templates/sshd_config.j2 dest=/etc/ssh/sshd_config
  notify: restart ssh
- group: name=sftponly

- copy:
    dest: /etc/fail2ban/jail.d/sshd.local
    content: |
      [sshd]
      enabled   = true
      filter    = sshd
      banaction = route
      backend   = systemd
      findtime  = 86400
      bantime   = 1209600
  notify: restart fail2ban
