---
- block:
    - docker_container:
        name: snmp-exporter
        image: prom/snmp-exporter
        state: started
        container_default_behavior: compatibility
        restart_policy: always
        log_driver: journald
        published_ports:
          - 9116:9116

  tags: snmp_exporter
